[project]
name = "archways-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "karol-prog42", email = "karljatienza@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
archways-assistant = "archways_assistant:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "jsonschema>=4.26.0",
    "pytest>=9.1.1",
    "rfc3339-validator>=0.1.4",
    "ruff>=0.16.10",
]
